import logging
from typing import Dict, Any, Literal
from pydantic import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import AIMessage
from app.core.state import IncidentState
from app.core.llm import local_llm

logger = logging.getLogger("Zephyr-Assessment")
logger.setLevel(logging.INFO)

# Strict Pydantic schema enforcing exactly how the Assessor must format its decision
class AssessmentResult(BaseModel):
    outcome: Literal["ATTACK_SUCCEEDED", "ATTACK_FAILED", "INCONCLUSIVE"] = Field(
        description="The definitive verdict on the alert."
    )
    confidence: float = Field(
        description="Confidence score between 0.0 and 1.0 based on evidence quality."
    )
    justification: str = Field(
        description="A strict, 2-sentence technical justification citing specific evidence."
    )

def assessment_node(state: IncidentState) -> Dict[str, Any]:
    """
    Verdict generation node. Consolidates tool outputs and enforces a strict
    JSON verdict schema to pass to the Defense node.
    """
    logger.info(f"[{state.incident_id}] === ASSESSMENT PHASE INITIATED ===")
    
    # Isolate the raw outputs generated by the ToolNode
    evidence_blocks = [msg.content for msg in state.messages if msg.type == "tool"]
    compiled_evidence = "\n".join(evidence_blocks) if evidence_blocks else "NO TOOL EVIDENCE GATHERED."
    
    logger.debug(f"[{state.incident_id}] Correlating gathered evidence: {compiled_evidence}")
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", """You are a SOC Assessor. 
        Review the evidence returned by the sandbox tools. 
        Determine if the attack succeeded, failed, or is inconclusive.
        You MUST output in strict structured JSON matching the provided schema."""),
        ("user", "Alert Signature: {signature}\nTarget: {target}\nCompiled Evidence:\n{evidence}")
    ])
    
    try:
        # Enforce structured output via Pydantic mapping
        structured_llm = local_llm.with_structured_output(AssessmentResult)
        chain = prompt | structured_llm
        
        result: AssessmentResult = chain.invoke({
            "signature": state.alert_signature,
            "target": state.target_ip,
            "evidence": compiled_evidence
        })
        
        logger.info(f"[{state.incident_id}] Assessment Complete: {result.outcome} (Confidence: {result.confidence})")
        logger.info(f"[{state.incident_id}] Justification: {result.justification}")
        
        return {
            "status": "ASSESSING",
            "assessment_outcome": result.outcome,
            "confidence": result.confidence,
            "assessment_justification": result.justification,
            "messages": [AIMessage(content=f"Verdict: {result.outcome} - {result.justification}")]
        }
        
    except Exception as e:
        logger.error(f"[{state.incident_id}] Assessor structured output failure: {str(e)}")
        # Fallback safeguard in case of LLM schema parsing failure
        return {
            "status": "ASSESSING",
            "assessment_outcome": "INCONCLUSIVE",
            "confidence": 0.0,
            "assessment_justification": f"Parser Failure: {str(e)}",
            "messages": [AIMessage(content="Verdict: INCONCLUSIVE due to parser failure.")]
        }